### PR TITLE
Upgrade to dotnet 6

### LINKED ISSUE #3: Upgrade sample azure-function to dotnet 6
Upgrade this project from dotnet core 3.1 to dotnet 6.

### PR DESCRIPTION
**Pull request by said-akram**
Upgrade from dotnet core 3.1 to dotnet 6.
Closes #3

### CODE REVIEW

**Review by danielrbroderick — APPROVED** [review]

**Review by MerlinDarkstar — APPROVED** [review]

**Comment by wpschaub** [comment]
@said-akram what version needs to be passed to ```netCoreVersion```? If I pass 4.1.1 I get this error:
image

**Review by wpschaub — COMMENTED** [review]
image. See PR conversation.

**Review by wpschaub — CHANGES_REQUESTED** [review]
@said-akram the *-start.yml template for the azure-function blueprint is passing 3.1.x to netCoreVersion. If I leave unchanged, I get this error:

```
Starting: Build
==============================================================================
Task         : .NET Core
Description  : Build, ***, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/opt/hostedtoolcache/dotnet/dotnet build /home/vsts/work/1/s/AzureDevOps.Automation.Pipeline.Sample.azure-function/Src/AzureFunction.Sample/AzureFunction.Sample/AzureFunction.Sample.csproj -dl:CentralLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.210.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.210.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" --configuration Release --no-restore
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

##[error]/opt/hostedtoolcache/dotnet/sdk/3.1.423/Microsoft.Common.CurrentVersion.targets(1177,5): Error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
/opt/hostedtoolcache/dotnet/sdk/3.1.423/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/home/vsts/work/1/s/AzureDevOps.Automation.Pipeline.Sample.azure-function/Src/AzureFunction.Sample/AzureFunction.Sample/AzureFunction.Sample.csproj]

Build FAILED.

/opt/hostedtoolcache/dotnet/sdk/3.1.423/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/home/vsts/work/1/s/AzureDevOps.Automation.Pipeline.Sample.azure-function/Src/AzureFunction.Sample/AzureFunction.Sample/AzureFunction.Sample.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.33
##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : /home/vsts/work/1/s/AzureDevOps.Automation.Pipeline.Sample.azure-function/Src/AzureFunction.Sample/AzureFunction.Sample/AzureFunction.Sample.csproj
Finishing: Build
```

If I change it to 4.1.x, I get this error:

```
Starting: Use .NET Core 4.1.x
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.207.2
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 4.1.x.
No matching sdk version could be found for specified version: 4.1.x Kindly note the preview versions are only considered in la*** version searches if Include Preview Versions checkbox is checked.
##[error]sdk version matching: 4.1.x could not be found
Finishing: Use .NET Core 4.1.x
```

**Comment by said-akram** [comment]
@wpschaub the *-start.yml template for the azure-function blueprint should be passing 6.x to netCoreVersion parameter.

**Review by wpschaub — APPROVED** [review]

**Pull request merged**
